### PR TITLE
allow full base64 jws parts during decode/verify/isValid. fixes #22

### LINKED ISSUE #22: base64 encoded tokens (with padding) rejected
I have tokens that appear to have been generated using base64 encoding instead of base64url encoding (3rd party auth system) and line 8 of verify-stream.js defines the pattern which the token must match. That doesn't currently include '=' padding, which is causing these tokens to be rejected as invalid.

I'm reading through the spec, and while it's pretty clear that token issuers should not include padding, it also appears to recommend that validation should allow for padding.

Thoughts?

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by omsmith** [comment]
So, the tricky bit.

As is, taking the s4, ecured input will be full padded base64. _node-jwa_ will happily accept that; however, it is against spec. We could transform them to be url-safe before passing it to jwa, but at that point the signature likely wouldn't be valid, as the signing implementation probably signed the full base64.

Despite my comments in #25, seems like it might be better/easier to not play nice with non-compliant implementations.

**Comment by taravancil** [comment]
A few thoughts on the conversation about [#25](https://github.com/brianloveswords/node-jws/pull/25) and your concerns:

The spec is clear that base64url encoding should be used. There are a [bunch of MUSTs]
(https://tools.ietf.org/html/rfc7515#page-20) that define how the values of a JWS object's members should be encoded, and they all say something like this:
> The "payload" member MUST be present and contain the value BASE64URL(JWS Payload).

Also, I'm not sure what you meant [here](https://github.com/brianloveswords/node-jws/pull/25#issuecomment-121771200)? I don't see how the reference for decoding base64url strings is lenient. It takes a base64url string, replaces `-` with `+` and `_` with `/` and then adds the appropriate number of `=` so the string can be decoded with standard base64Decode implementations.

So, :+1: to your comment that it's better/easier comply with the spec. Implementing base64 is not a good idea and could lead to confusion when folks use this package.

**Comment by brianloveswords** [comment]
Yeah, if the spec's using MUST I say we stay compliant. Closing this for now!

**Comment by omsmith** [comment]
Sounds good to me

**Pull request closed without merging**
